- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: decrypt config into env.ts
    template:
      src="../env.ts.j2"
      dest="../env.ts"